define(['jquery', 'core/ajax'], function($, ajax) {

    var UserFormHandler = {

        init: function() {
            this.setupUsernameGenerator();
            this.setupMarcaUoHandler();
        },

        setupUsernameGenerator: function() {
            $('.ocultar-elemento').hide();

            var firstname_ = $('#id_firstname');
            var lastname_ = $('#id_lastname');
            var domain = '@norte19.com'; // Default value

           


            $('#id_firstname, #id_lastname').on('input', function() {
                var firstname = this.stringToSlug(firstname_.val());
                var initial_firstname = firstname.substr(0, 1);
                var middlename = this.formatMiddlename(lastname_.val());
                var autogenerated = initial_firstname + middlename;
                var default_username = autogenerated + this.getFormattedDate();
                var default_email = default_username + domain;

                $('#id_username').val(default_username);
                $('#id_newpassword').val(default_username);
                $('#id_email').val(default_email);
            }.bind(this));
        },

        formatMiddlename: function(email) {
            if (!email) return email;
            email = this.stringToSlug(email);
            var pieces = email.split('_');
            var response = "";
            var middlenameCompleted = false;

            for (var i = 0; i < pieces.length; i++) {
                var current_word = pieces[i];
                if (!middlenameCompleted) {
                    middlenameCompleted = current_word.length > 2 && current_word !== 'del';
                    response += current_word;
                }
            }
            return response;
        },

        getFormattedDate: function() {
            var today = new Date();
            var year = today.getFullYear().toString().substr(2);
            var month = today.getMonth() + 1;
            var day = today.getDate();

            if (month < 10) month = '0' + month;
            if (day < 10) day = '0' + day;

            return year + month + day;
        },

        stringToSlug: function(str) {
            str = str.replace(/^\s+|\s+$/g, '').toLowerCase();
            var from = "àáäâèéëêìíïîòóöôùúüûñç·/-,:;";
            var to = "aaaaeeeeiiiioooouuuunc______";
            for (var i = 0, l = from.length; i < l; i++) {
                str = str.replace(new RegExp(from.charAt(i), 'g'), to.charAt(i));
            }
            return str.replace(/[^a-z0-9 -]/g, '')
                      .replace(/\s+/g, '_')
                      .replace(/-+/g, '_');
        },

        setupMarcaUoHandler: function() {
            var self = this;
            var informacion_marca_uo = [{ name: 'request_type', value: 'get_all_marcas_uo' }];
            var marcas = [];

            $("#id_profile_field_marca").on('click', function() {
                alert("Si modificas este campo, se verá afectada la relación de unidad operativa y marca");
            });

            $.ajax({
                type: "POST",
                url: "services.php",
                data: informacion_marca_uo,
                dataType: "json"
            }).done(function(data) {
                if (data.status === 'ok') {
                    marcas = data.data;
                    self.loadMarcaInstitution(marcas);
                }
            });

            $("select").on('change', function() {
                var puestomarca = $("#id_department").val() + " - " + $("#id_profile_field_marca").val();
                $("#id_profile_field_Puestomarca").val(puestomarca);
            });

            $("#id_institution").on('change', function() {
                $('#id_profile_field_marca option:selected').prop('selected', false);
                var hotel = $(this).val();
                self.changeMarca(hotel, marcas);
                self.reloadInstitutions(hotel);
            });
        },

        loadMarcaInstitution: function(marcas) {
            var hotel = $("#id_institution").val();
            this.changeMarca(hotel, marcas);
            this.reloadInstitutions(hotel);
        },

        changeMarca: function(hotel, marcas) {
            $("#id_profile_field_marca option").prop('selected', false);
            marcas.forEach(function(marca) {
                if (marca.value.indexOf(hotel) !== -1) {
                    $("#id_profile_field_marca option[value='" + marca.name + "']").prop('selected', true);
                    var puestomarca = $("#id_department").val() + " - " + $("#id_profile_field_marca").val();
                    $("#id_profile_field_Puestomarca").val(puestomarca);
                }
            });
        },

        reloadInstitutions: function(institution) {
            ajax.call([{
                methodname: 'local_hoteles_city_dashboard_get_institutions_ggc',
                args: {
                    data: { institution: institution }
                }
            }])[0].done(function(response) {
                var data = JSON.parse(response);
                var select = document.getElementById("id_department");
                var puestoUser = select.value;
                select.innerHTML = '';

                for (var key in data) {
                    if (data.hasOwnProperty(key)) {
                        var optionElement = document.createElement("option");
                        optionElement.value = key;
                        optionElement.textContent = data[key];
                        select.appendChild(optionElement);
                    }
                }

                select.value = puestoUser;
            });
        }
    };

    return UserFormHandler;
});